name: Test
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    name: Terraform Tests
    runs-on: ubuntu-latest
    steps:
      #############################
      # Configure AWS credentials #
      #############################
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_TESTING_ACCOUNT_ID }}:role/${{ vars.AWS_TESTING_ROLE }}
          aws-region: ${{ vars.AWS_TESTING_REGION }}
          mask-aws-account-id: false
